version: 1.1.0.{build}

image:
 - Visual Studio 2022

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
 - C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm"

build_script:
 - C:\msys64\usr\bin\bash -lc "make -C /c/projects/thlog clean all UNICODE=0 DEBUG=0"
 - C:\msys64\usr\bin\bash -lc "make -C /c/projects/thlog clean all UNICODE=0 DEBUG=1"
 - C:\msys64\usr\bin\bash -lc "make -C /c/projects/thlog clean all UNICODE=1 DEBUG=0"
 - C:\msys64\usr\bin\bash -lc "make -C /c/projects/thlog clean all UNICODE=1 DEBUG=1"
